general {
    lock_cmd = pidof hyprlock || hyprlock      # avoid starting multiple hyprlock instances
    before_sleep_cmd = hyprlock                # lock before sleeping
    after_sleep_cmd = hyprctl dispatch dpms on # to avoid having to press a key twice to turn on the display
}

listener {
    timeout = 180                        # 3 min
    on-timeout = brightnessctl -s set 5% # reduce monitor backlight
    on-resume = brightnessctl -r         # restore monitor backlight
}

listener {
    timeout = 300         # 5 min
    on-timeout = hyprlock # lock the system
}

listener {
    timeout = 360                                            # 6 min
    on-timeout = hyprctl dispatch dpms off                   # screen off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r # screen on & restore monitor backlight
}

listener {
    timeout = 1800                 # 30 min
    on-timeout = systemctl suspend # system suspend
}
