$font = SF Pro Display, Monospace 

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
}

# DAY
label {
    monitor =
    text = cmd[update:60000] date +"%A" # update every 60 seconds

    font_size = 90
    font_family = $font Bold

    position = 0, 130
    halign = center
    valign = center
}

# DATE & MONTH
label {
    monitor =
    text = cmd[update:60000] date +"%d %b" # update every 60 seconds

    font_size = 40
    font_family = $font Bold

    position = 0, 30
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = - $TIME -

    font_size = 20
    font_family = $font Bold

    position = 0, -20 
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    fade_on_empty = false
    hide_input = false    
    fail_text = $PAMFAIL

    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(255, 255, 255, .1)    

    rounding = -1
    border_size = 0
    border_color = rgba(255, 255, 255, 0)

    font_family = $font
    font_color = rgb(222, 222, 222)

    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true

    position = 0, -140
    halign = center
    valign = center
}

# LAYOUT
label {
    monitor =
    text = $LAYOUT[en,ru]
    onclick = hyprctl switchxkblayout all next

    font_family = $font Bold
    font_size = 24

    position = 180, -140
    halign = center
    valign = center
}

