# https://github.com/fairyglade/ly/blob/master/res/config.ini

### ANIMATION ###

animation = colormix
animation_timeout_sec = 0

# doom
doom_fire_height = 6
doom_fire_spread = 2
doom_top_color = 0x009F2707
doom_middle_color = 0x00C78F17
doom_bottom_color = 0x00FFFFFF

# matrix
cmatrix_fg = 0x0000FF00
cmatrix_head_col = 0x01FFFFFF
cmatrix_min_codepoint = 0x21
cmatrix_max_codepoint = 0x7B

# colormix
colormix_col1 = 0x80008844
colormix_col2 = 0x80004488
colormix_col3 = 0x00161616

# gameoflife
gameoflife_entropy_interval = 10
gameoflife_fg = 0x0000FF00
gameoflife_frame_delay = 6
gameoflife_initial_density = 0.4

# dur_file
dur_file_path = /etc/ly/example.dur
dur_x_offset = 0
dur_y_offset = 0

### COLORS ###

full_color = true

bg = 0x00000000
fg = 0x00FFFFFF

error_bg = 0x00000000
error_fg = 0x01FF0000

border_fg = 0x00FFFFFF

### MAIN BOX ###

blank_box = true
box_title = null

margin_box_h = 2
margin_box_v = 1

hide_borders = false

input_len = 34

### AUTH ###

auth_fails = 10

allow_empty_password = true
clear_password = true

asterisk = 0x2022

auto_login_service = ly-autologin
auto_login_session = null
auto_login_user = null

default_input = password

save = true

### BIG CLOCK ###

bigclock = en
bigclock_12hr = false
bigclock_seconds = false

### COMMANDS ###

shutdown_cmd = /sbin/shutdown -a now
shutdown_key = F1

restart_cmd = /sbin/shutdown -r now
restart_key = F2

sleep_cmd = null
sleep_key = F3

hibernate_cmd = null
hibernate_key = F4

brightness_down_cmd = /usr/bin/brightnessctl -q -n s 10%-
brightness_down_key = F5

brightness_up_cmd = /usr/bin/brightnessctl -q -n s +10%
brightness_up_key = F6

inactivity_cmd = null
inactivity_delay = 0

x_cmd = /usr/bin/X
xauth_cmd = /usr/bin/xauth

login_cmd = null
logout_cmd = null

start_cmd = null
setup_cmd = /etc/ly/setup.sh

### CORNERS ###

hide_key_hints = false
hide_keyboard_locks = false
hide_version_string = true

battery_id = BAT0
clock = %a %d.%m.%Y %H:%M:%S

### SESSIONS & FILES ###

# sessions
custom_sessions = /etc/ly/custom-sessions
waylandsessions = /usr/share/wayland-sessions
xsessions = /usr/share/xsessions

# logs
ly_log = /var/log/ly.log
session_log = .local/state/ly-session.log

# other files
login_defs_path = /etc/login.defs
xinitrc = ~/.xinitrc

### MISC ###

lang = en
numlock = false

initial_info_text = null
text_in_center = false

edge_margin = 0

min_refresh_delta = 5

path = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

service_name = ly

vi_default_mode = normal
vi_mode = false
