# --- #
# Autostart commands
# --- #

exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = waybar

exec = sh -c "if [ -z $(pidof hyprpaper) ]; then hyprpaper & sleep 1s; fi; $scripts_dir/random-wallpaper.sh"
exec = hyprshade auto
