# --- #
# Environment variables
# https://wiki.hypr.land/Configuring/Environment-variables/
# --- #

# cursor
env = HYPRCURSOR_THEME, theme_Kasane Teto Theme
env = XCURSOR_SIZE,    24
env = HYPRCURSOR_SIZE, 24

# XDG specifications
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE,    wayland
env = XDG_SESSION_DESKTOP, Hyprland

# Qt
env = QT_AUTO_SCREEN_SCALE_FACTOR,         1
env = QT_QPA_PLATFORM,                     wayland;xcb
env = QT_QPA_PLATFORM_THEME,               qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION, 1

# Mozilla
env = MOZ_ENABLE_WAYLAND, 1

# Ozone
env = OZONE_PLATFORM,               wayland
env = ELECTRON_OZONE_PLATFORM_HINT, wayland

# toolkit backend
env = GDK_BACKEND,     wayland, x11, *
env = SDL_VIDEODRIVER, wayland
env = CLUTTER_BACKEND, wayland
