# --- #
# Window & layer rules
# https://wiki.hypr.land/Configuring/Window_Rules/
# --- #

# ignore maximize requests
windowrule {
    name = ignore-maximize
    suppress_event = maximize
    
    match:class = .*
}

# fix some dragging issues with XWayland
windowrule {
    name = xwayland-drag-fix
    no_focus = on
    
    match:class = ^$
    match:title = ^$
    match:xwayland = 1
    match:float = 1
    match:fullscreen = 0
    match:pin = 0
}

# wofi blur
layerrule {
    name = wofi-blur
    blur = on
    ignore_alpha = 0.01
    blur_popups = on
    dim_around = on
    
    match:namespace = wofi
}

# waybar blur
layerrule {
    name = waybar-blur
    blur = on
    ignore_alpha = 0.01
    blur_popups = on
    
    match:namespace = waybar
}

# dunst blur
layerrule {
    name = dunst-blur
    blur = on
    ignore_alpha = 0.01
    blur_popups = on
    
    match:namespace = dunst
}
